### ISSUE TITLE
Broadcasting Vs VideoConferencing

### ISSUE THREAD

**Issue by cvkmohan** [membraneframework/membrane_videoroom#100]
In the README, you have written that -
```
At the same time, for broadcasting multimedia to thousands of viewers, other mechanisms need to be used, and it can be achieved with the use of the Membrane Framework. We invite you to take a look at other [Membrane demos](https://github.com/membraneframework/membrane_demo)
```
Does https://github.com/membraneframework-labs/membrane_live come into one of the demos which explain the feature? I mean, this looks a far complete example than what you have given in the regular demos.

**Comment by cvkmohan** [comment]
Sorry for bumping this up. I know it is not an issue - but - I have no idea which other place to ask this question.

**Comment by mat-hek** [comment]
> Sorry for bumping this up. I know it is not an issue - but - I have no idea which other place to ask this question.

Hey, sorry for a late reply, the place is https://discord.gg/aadhKeaqAY ;) `membrane_live` is a standalone app, so you can take it as an example, but it's going to be hard to customize for your needs. The better option would be to use https://github.com/jellyfish-dev/jellyfish (standalone server) or https://github.com/jellyfish-dev/membrane_rtc_engine (Elixir library). Please ask on discord if you have any further questions.
